#include "constants.h"

const char * NEWS[] = {
	"NASA now almost positive Mars is rockey.",
	"Hubble space telescope finds men from Venus, women from Mars.",
	"Niel DeGrasse Tyson lets slip that he's been to Mars.",
	"NASA designers release flirty new space skirt.",
	"Conspiracy theorists convinced Terran government is behind NASA.",
	"New space camp program allows kids to simulate frustration over lack of funding.",
	"China launches first willing manned mission into space.",
	"NASA inadvertantly alaunches unmanned space shuttle.",
	"NASA mission control suprises space shuttle discovery crew with two-second countdown.",
	"NASA continues search for planet capable fo supporting NASA.",
	"Space shuttle endevor asks, 'Whats in it for me?'",
	"Hubble space telescope destroyed by Bill Gate's space fortress.",
	"Coke sponsored rover finds evidence of Dasani on Mars.",
	"Bush still working on manned mission to Mars, quietly in spare time.",
	"Taylor Swift now in long distance relationship with curriosity rover.",
	"NASA calls it a mission as curiosity rover fills up whole two-gigabyte memory card.",
	"Pope tweets picture of self with God.",
	"Bush vows to discover and legalize aliens on American, Martian soil.",
	"Majority of Americans thought we already had a moon-base.",
	"Radiation leaks cause Martian wheat crop to turn polka-dot.",
	"North Korea vows to end the war before Great Leader's birthday.",
	"Kim Jong Un announces plan to bring moon to North Korea.",
	"Colorblind players of Red Space overjoyed by its orange-green color scheme.",
	"Factory workers overjoyed to find unexploded warhead is 'reusable.'",
	"Local man attempts DIY nuclear warhead. There were no survivors.",
	"Earth wonders where moon went.",
	"Mars thanks Earth for eradicating Ebola.",
	"Roaches of Mars, please stay within designated reserves.",
	"Martians realease statemnt to the Terran Alliance, 'We're CRIMSON, quit calling us red.'",
	"Death toll today on the Red Plannet remains a consistent zero. Unfortunantly, billions of redshirt casualties have been reported.",
	"Man licks uranium, gains 'SUPER TASTE.'"
};